version: 0.2

phases:
  install:
    commands:
      # installation
      - apt-get update -y
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:openjdk-r/ppa
      - apt-get update -y
      - apt-get install -y openjdk-8-jdk
      - apt-get install -y maven

  pre_build:
    commands:

  build:
    commands:
      - echo Maven Build ...
      - mvn clean package

       
artifacts:
     files:
      - target/spring-boot.jar